/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SuggestionsRouteImport } from './routes/suggestions'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as GithubRouteImport } from './routes/github'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BridgeRouteImport } from './routes/bridge'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsAuthRouteImport } from './routes/settings.auth'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HooksSyncGithubRouteImport } from './routes/hooks/sync-github'
import { Route as HooksRunCliSchedulesRouteImport } from './routes/hooks/run-cli-schedules'
import { Route as ApiZohoCallbackRouteImport } from './routes/api/zoho.callback'
import { Route as ApiPublicBridgeInstallRouteImport } from './routes/api/public/bridge-install'
import { Route as ApiPublicBridgeDaemonRouteImport } from './routes/api/public/bridge-daemon'
import { Route as ApiCliStreamRouteImport } from './routes/api/cli.stream'
import { Route as ApiCliSplatRouteImport } from './routes/api/cli.$'
import { Route as ApiPublicHooksFrontierScanRouteImport } from './routes/api/public/hooks/frontier-scan'
import { Route as ApiPublicBridgeSplatRouteImport } from './routes/api/public/bridge.$'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestionsRoute = SuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeRoute = BridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuthRoute = SettingsAuthRouteImport.update({
  id: '/settings/auth',
  path: '/settings/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksSyncGithubRoute = HooksSyncGithubRouteImport.update({
  id: '/hooks/sync-github',
  path: '/hooks/sync-github',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksRunCliSchedulesRoute = HooksRunCliSchedulesRouteImport.update({
  id: '/hooks/run-cli-schedules',
  path: '/hooks/run-cli-schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZohoCallbackRoute = ApiZohoCallbackRouteImport.update({
  id: '/api/zoho/callback',
  path: '/api/zoho/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeInstallRoute = ApiPublicBridgeInstallRouteImport.update({
  id: '/api/public/bridge-install',
  path: '/api/public/bridge-install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeDaemonRoute = ApiPublicBridgeDaemonRouteImport.update({
  id: '/api/public/bridge-daemon',
  path: '/api/public/bridge-daemon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliStreamRoute = ApiCliStreamRouteImport.update({
  id: '/api/cli/stream',
  path: '/api/cli/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliSplatRoute = ApiCliSplatRouteImport.update({
  id: '/api/cli/$',
  path: '/api/cli/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksFrontierScanRoute =
  ApiPublicHooksFrontierScanRouteImport.update({
    id: '/api/public/hooks/frontier-scan',
    path: '/api/public/hooks/frontier-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeSplatRoute = ApiPublicBridgeSplatRouteImport.update({
  id: '/api/public/bridge/$',
  path: '/api/public/bridge/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/bridge': typeof BridgeRoute
  '/chat': typeof ChatRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/github': typeof GithubRoute
  '/legal': typeof LegalRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/suggestions': typeof SuggestionsRoute
  '/terminal': typeof TerminalRoute
  '/hooks/run-cli-schedules': typeof HooksRunCliSchedulesRoute
  '/hooks/sync-github': typeof HooksSyncGithubRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/api/cli/$': typeof ApiCliSplatRoute
  '/api/cli/stream': typeof ApiCliStreamRoute
  '/api/public/bridge-daemon': typeof ApiPublicBridgeDaemonRoute
  '/api/public/bridge-install': typeof ApiPublicBridgeInstallRoute
  '/api/zoho/callback': typeof ApiZohoCallbackRoute
  '/api/public/bridge/$': typeof ApiPublicBridgeSplatRoute
  '/api/public/hooks/frontier-scan': typeof ApiPublicHooksFrontierScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/bridge': typeof BridgeRoute
  '/chat': typeof ChatRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/github': typeof GithubRoute
  '/legal': typeof LegalRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/suggestions': typeof SuggestionsRoute
  '/terminal': typeof TerminalRoute
  '/hooks/run-cli-schedules': typeof HooksRunCliSchedulesRoute
  '/hooks/sync-github': typeof HooksSyncGithubRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/api/cli/$': typeof ApiCliSplatRoute
  '/api/cli/stream': typeof ApiCliStreamRoute
  '/api/public/bridge-daemon': typeof ApiPublicBridgeDaemonRoute
  '/api/public/bridge-install': typeof ApiPublicBridgeInstallRoute
  '/api/zoho/callback': typeof ApiZohoCallbackRoute
  '/api/public/bridge/$': typeof ApiPublicBridgeSplatRoute
  '/api/public/hooks/frontier-scan': typeof ApiPublicHooksFrontierScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/bridge': typeof BridgeRoute
  '/chat': typeof ChatRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/github': typeof GithubRoute
  '/legal': typeof LegalRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/suggestions': typeof SuggestionsRoute
  '/terminal': typeof TerminalRoute
  '/hooks/run-cli-schedules': typeof HooksRunCliSchedulesRoute
  '/hooks/sync-github': typeof HooksSyncGithubRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/api/cli/$': typeof ApiCliSplatRoute
  '/api/cli/stream': typeof ApiCliStreamRoute
  '/api/public/bridge-daemon': typeof ApiPublicBridgeDaemonRoute
  '/api/public/bridge-install': typeof ApiPublicBridgeInstallRoute
  '/api/zoho/callback': typeof ApiZohoCallbackRoute
  '/api/public/bridge/$': typeof ApiPublicBridgeSplatRoute
  '/api/public/hooks/frontier-scan': typeof ApiPublicHooksFrontierScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agents'
    | '/auth'
    | '/bridge'
    | '/chat'
    | '/console'
    | '/dashboard'
    | '/github'
    | '/legal'
    | '/profile'
    | '/projects'
    | '/suggestions'
    | '/terminal'
    | '/hooks/run-cli-schedules'
    | '/hooks/sync-github'
    | '/invite/$token'
    | '/settings/auth'
    | '/api/cli/$'
    | '/api/cli/stream'
    | '/api/public/bridge-daemon'
    | '/api/public/bridge-install'
    | '/api/zoho/callback'
    | '/api/public/bridge/$'
    | '/api/public/hooks/frontier-scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agents'
    | '/auth'
    | '/bridge'
    | '/chat'
    | '/console'
    | '/dashboard'
    | '/github'
    | '/legal'
    | '/profile'
    | '/projects'
    | '/suggestions'
    | '/terminal'
    | '/hooks/run-cli-schedules'
    | '/hooks/sync-github'
    | '/invite/$token'
    | '/settings/auth'
    | '/api/cli/$'
    | '/api/cli/stream'
    | '/api/public/bridge-daemon'
    | '/api/public/bridge-install'
    | '/api/zoho/callback'
    | '/api/public/bridge/$'
    | '/api/public/hooks/frontier-scan'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agents'
    | '/auth'
    | '/bridge'
    | '/chat'
    | '/console'
    | '/dashboard'
    | '/github'
    | '/legal'
    | '/profile'
    | '/projects'
    | '/suggestions'
    | '/terminal'
    | '/hooks/run-cli-schedules'
    | '/hooks/sync-github'
    | '/invite/$token'
    | '/settings/auth'
    | '/api/cli/$'
    | '/api/cli/stream'
    | '/api/public/bridge-daemon'
    | '/api/public/bridge-install'
    | '/api/zoho/callback'
    | '/api/public/bridge/$'
    | '/api/public/hooks/frontier-scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentsRoute: typeof AgentsRoute
  AuthRoute: typeof AuthRoute
  BridgeRoute: typeof BridgeRoute
  ChatRoute: typeof ChatRoute
  ConsoleRoute: typeof ConsoleRoute
  DashboardRoute: typeof DashboardRoute
  GithubRoute: typeof GithubRoute
  LegalRoute: typeof LegalRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  SuggestionsRoute: typeof SuggestionsRoute
  TerminalRoute: typeof TerminalRoute
  HooksRunCliSchedulesRoute: typeof HooksRunCliSchedulesRoute
  HooksSyncGithubRoute: typeof HooksSyncGithubRoute
  InviteTokenRoute: typeof InviteTokenRoute
  SettingsAuthRoute: typeof SettingsAuthRoute
  ApiCliSplatRoute: typeof ApiCliSplatRoute
  ApiCliStreamRoute: typeof ApiCliStreamRoute
  ApiPublicBridgeDaemonRoute: typeof ApiPublicBridgeDaemonRoute
  ApiPublicBridgeInstallRoute: typeof ApiPublicBridgeInstallRoute
  ApiZohoCallbackRoute: typeof ApiZohoCallbackRoute
  ApiPublicBridgeSplatRoute: typeof ApiPublicBridgeSplatRoute
  ApiPublicHooksFrontierScanRoute: typeof ApiPublicHooksFrontierScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggestions': {
      id: '/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof SuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/auth': {
      id: '/settings/auth'
      path: '/settings/auth'
      fullPath: '/settings/auth'
      preLoaderRoute: typeof SettingsAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/sync-github': {
      id: '/hooks/sync-github'
      path: '/hooks/sync-github'
      fullPath: '/hooks/sync-github'
      preLoaderRoute: typeof HooksSyncGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/run-cli-schedules': {
      id: '/hooks/run-cli-schedules'
      path: '/hooks/run-cli-schedules'
      fullPath: '/hooks/run-cli-schedules'
      preLoaderRoute: typeof HooksRunCliSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zoho/callback': {
      id: '/api/zoho/callback'
      path: '/api/zoho/callback'
      fullPath: '/api/zoho/callback'
      preLoaderRoute: typeof ApiZohoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge-install': {
      id: '/api/public/bridge-install'
      path: '/api/public/bridge-install'
      fullPath: '/api/public/bridge-install'
      preLoaderRoute: typeof ApiPublicBridgeInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge-daemon': {
      id: '/api/public/bridge-daemon'
      path: '/api/public/bridge-daemon'
      fullPath: '/api/public/bridge-daemon'
      preLoaderRoute: typeof ApiPublicBridgeDaemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/stream': {
      id: '/api/cli/stream'
      path: '/api/cli/stream'
      fullPath: '/api/cli/stream'
      preLoaderRoute: typeof ApiCliStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/$': {
      id: '/api/cli/$'
      path: '/api/cli/$'
      fullPath: '/api/cli/$'
      preLoaderRoute: typeof ApiCliSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/frontier-scan': {
      id: '/api/public/hooks/frontier-scan'
      path: '/api/public/hooks/frontier-scan'
      fullPath: '/api/public/hooks/frontier-scan'
      preLoaderRoute: typeof ApiPublicHooksFrontierScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/$': {
      id: '/api/public/bridge/$'
      path: '/api/public/bridge/$'
      fullPath: '/api/public/bridge/$'
      preLoaderRoute: typeof ApiPublicBridgeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentsRoute: AgentsRoute,
  AuthRoute: AuthRoute,
  BridgeRoute: BridgeRoute,
  ChatRoute: ChatRoute,
  ConsoleRoute: ConsoleRoute,
  DashboardRoute: DashboardRoute,
  GithubRoute: GithubRoute,
  LegalRoute: LegalRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  SuggestionsRoute: SuggestionsRoute,
  TerminalRoute: TerminalRoute,
  HooksRunCliSchedulesRoute: HooksRunCliSchedulesRoute,
  HooksSyncGithubRoute: HooksSyncGithubRoute,
  InviteTokenRoute: InviteTokenRoute,
  SettingsAuthRoute: SettingsAuthRoute,
  ApiCliSplatRoute: ApiCliSplatRoute,
  ApiCliStreamRoute: ApiCliStreamRoute,
  ApiPublicBridgeDaemonRoute: ApiPublicBridgeDaemonRoute,
  ApiPublicBridgeInstallRoute: ApiPublicBridgeInstallRoute,
  ApiZohoCallbackRoute: ApiZohoCallbackRoute,
  ApiPublicBridgeSplatRoute: ApiPublicBridgeSplatRoute,
  ApiPublicHooksFrontierScanRoute: ApiPublicHooksFrontierScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
